### ISSUE TITLE
Add concurrency to our workflows

### ISSUE THREAD

**Issue by yannick-roeder** [bakdata/ci-templates#158]
Ideally the previous workflow is cancelled when the newer workflow is already running. This can be achieved with [workflow concurrency](https://docs.github.com/en/actions/using-jobs/using-concurrency). Adding this to every workflow should be sufficient:

```yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-docker
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}
```

Note that the suffix of the group is always specific to the workflow to avoid that different workflows cancel each other in the same run.
